export const ADD_STUDENT = 'ADD_STUDENT';
export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCESS = 'LOGIN_SUCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
